export default {
  // Counter
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  CHECK_SQUARE: 'CHECK_SQUARE',
  INITIAL_SQUARE: 'INITIAL_SQUARE',
  CLEAR_SQUARE: 'CLEAR_SQUARE',
  SET_WINNER: 'SET_WINNER',
  JUMP: 'JUMP',
}

